const mongoose = require("mongoose");
const House = require("../models/House.model");
require("./index");
// const flat1 = require("./housepictures/flat1.jpg")


let houses = [
  {
    name: "Beautiful apartment",
    location: "Peru",
    pricepernight: 50,
    maxnumberofdays: 7,
    rooms: 3,
    type: "Apartment",
    animaltype: "Dog",
    maxsizeofanimal: "Big",
    maxnumberofanimals: 3,
    photo: "/housepictures/flat1.jpg"
  },
  {
    name: "House for cats",
    location: "USA",
    pricepernight: 55,
    maxnumberofdays: 3,
    rooms: 2,
    type: "House",
    animaltype: "Cat",
    maxsizeofanimal: "Medium",
    maxnumberofanimals: 2,
    photo: "/housepictures/flat1.jpg",
  },
  {
    name: "Great flat to visit with your dog!",
    location: "Brazil",
    pricepernight: 40,
    maxnumberofdays: 3,
    rooms: 1,
    type: "Flat",
    animaltype: "Dog",
    maxsizeofanimal: "Small",
    maxnumberofanimals: 1,
    photo: "/housepictures/flat1.jpg",
  },
  {
    name: "Farm for Animals",
    location: "France",
    pricepernight: 100,
    maxnumberofdays: 5,
    rooms: 2,
    type: "Farm",
    animaltype: "Cat",
    maxsizeofanimal: "Giant",
    maxnumberofanimals: 2,
    photo: "/housepictures/flat1.jpg",
  },
  {
    name: "Cat's room",
    location: "Italy",
    pricepernight: 15,
    maxnumberofdays: 10,
    rooms: 1,
    type: "Room",
    animaltype: "Cat",
    maxsizeofanimal: "Medium",
    maxnumberofanimals: 1,
    photo: "/housepictures/flat1.jpg",
  },
  {
    name: "Vacation house",
    location: "Nederlands",
    pricepernight: 80,
    maxnumberofdays: 10,
    rooms: 4,
    type: "House",
    animaltype: "Dog",
    maxsizeofanimal: "Big",
    maxnumberofanimals: 2,
    photo: "/housepictures/flat1.jpg",
  },
  {
    name: "Quiet Apartment",
    location: "Mexico",
    pricepernight: 30,
    maxnumberofdays: 14,
    rooms: 2,
    type: "Apartment",
    animaltype: "Cat",
    maxsizeofanimal: "Small",
    maxnumberofanimals: 2,
    photo: "/housepictures/flat1.jpg",
  },
  {
    name: "Nice flat",
    location: "Czech Republic",
    pricepernight: 20,
    maxnumberofdays: 8,
    rooms: 1,
    type: "Flat",
    animaltype: "Cat",
    maxsizeofanimal: "Big",
    maxnumberofanimals: 3,
    photo: "/housepictures/flat1.jpg",
  },
  {
    name: "Farm for rent",
    location: "Canada",
    pricepernight: 90,
    maxnumberofdays: 10,
    rooms: 5,
    type: "Farm",
    animaltype: "Dog",
    maxsizeofanimal: "Giant",
    maxnumberofanimals: 6,
    photo: "/housepictures/flat1.jpg",
  },
  // {
  //   name: "House for turtles",
  //   location: "Colorado, USA",
  //   pricepernight: 55,
  //   maxnumberofdays: 3,
  //   rooms: 2,
  //   type: "House",
  //   animaltype: "Cat",
  //   maxsizeofanimal: "Medium",
  //   maxnumberofanimals: 2,
  // },
  // {
  //   name: "House for turtles",
  //   location: "Colorado, USA",
  //   pricepernight: 55,
  //   maxnumberofdays: 3,
  //   rooms: 2,
  //   type: "House",
  //   animaltype: "Cat",
  //   maxsizeofanimal: "Medium",
  //   maxnumberofanimals: 2,
  // },
  // {
  //   name: "House for turtles",
  //   location: "Colorado, USA",
  //   pricepernight: 55,
  //   maxnumberofdays: 3,
  //   rooms: 2,
  //   type: "House",
  //   animaltype: "Cat",
  //   maxsizeofanimal: "Medium",
  //   maxnumberofanimals: 2,
  // },
  // {
  //   name: "House for turtles",
  //   location: "Colorado, USA",
  //   pricepernight: 55,
  //   maxnumberofdays: 3,
  //   rooms: 2,
  //   type: "House",
  //   animaltype: "Cat",
  //   maxsizeofanimal: "Medium",
  //   maxnumberofanimals: 2,
  // },
  // {
  //   name: "House for turtles",
  //   location: "Colorado, USA",
  //   pricepernight: 55,
  //   maxnumberofdays: 3,
  //   rooms: 2,
  //   type: "House",
  //   animaltype: "Cat",
  //   maxsizeofanimal: "Medium",
  //   maxnumberofanimals: 2,
  // },
  // {
  //   name: "House for turtles",
  //   location: "Colorado, USA",
  //   pricepernight: 55,
  //   maxnumberofdays: 3,
  //   rooms: 2,
  //   type: "House",
  //   animaltype: "Cat",
  //   maxsizeofanimal: "Medium",
  //   maxnumberofanimals: 2,
  // },
  // {
  //   name: "House for turtles",
  //   location: "Colorado, USA",
  //   pricepernight: 55,
  //   maxnumberofdays: 3,
  //   rooms: 2,
  //   type: "House",
  //   animaltype: "Cat",
  //   maxsizeofanimal: "Medium",
  //   maxnumberofanimals: 2,
  // },
];
House.insertMany(houses)
  .then((addedHouses) => {
    addedHouses.map((house) => console.log(house.name)); // to console.log each added name
  })
  .catch((err) => {
    console.log("Error with mongoose method", err);
  });
